### ISSUE TITLE
URL connection instructions on nativeplanet.io/software

### ISSUE THREAD

**Issue by jmahhh** [Native-Planet/GroundSeg#120]
Hello, just wanted to note --

I installed groundseg on a droplet and use remote desktop to connect to ubuntu desktop - connecting to either nativeplanet.local or http://127.0.0.1:27016 returned a 404, but connecting to http://127.0.0.1 itself did work.

Cheers

**Comment by yapishu** [comment]
Hi @jmahhh -- GroundSeg is not meant to be installed on a remote server, it's meant to run on a device on your local network. 

I'm unsure where the http://127.0.0.1:27016/ URL came from, but the `nativeplanet.local` address 1) relies on the device being on your local network, and 2) uses your device's hostname -- so if your computer's name is `johncomputer`, you would go to `johncomputer.local`. For devices with ColonyOS installed, the hostname is `nativeplanet`.

**Comment by mopfel-winrux** [comment]
`:27016` is the API port
