### ISSUE TITLE
UI suggestion: GroundSeg should allow custom background image and sigil color

### ISSUE THREAD

**Issue by rdp-studio** [Native-Planet/GroundSeg#136]
1) I think customization is very important. The default background image is not very good in my opinion.

2) I customized the sigil color in Urbit, but when I returned to GroundSeg, it didn't show it, which didn't look good.

**Comment by nallux-dozryl** [comment]
Hi @rdp-studio,

Thanks for the suggestion. Customization of the WebUI is indeed a cool addition. Unfortunately it is currently not high on our list of priorities. That being said, we appreciate your suggestion and will discuss internally about the feasibility of this.

While we appreciate your interest in our software and welcome any feedback, I wanted to clarify that GitHub issues are reserved for reporting problems or issues with the software.

If you have a suggestion or feature request, we encourage you to share it with us in our public group on Urbit: `~raldeg/nativeplanet`.

Thank you for your understanding, and please don't hesitate to reach out if you have any further questions or concerns.

~nallux-dozryl
