### ISSUE TITLE
Ship disappeared from GroundSeg interface and is not running

### ISSUE THREAD

**Issue by KeepCreatingOnline** [Native-Planet/GroundSeg#158]
Please help. My star ~lanlyd is gone from the interface. My personal ship ~navluc-latmes was unaffected. 

Here are the loggs. 
[groundseg.txt](https://github.com/Native-Planet/GroundSeg/files/11713652/groundseg.txt)

**Comment by yapishu** [comment]
Hi @KeepCreatingOnline , I can see that lanlyd's config json somehow got corrupted:

```
2023-06-10 21:32:03.948557 Bug: Failed to load lanlyd.json: Expecting value: line 1 column 1 (char 0)
```

Don't fret about your data though, because your pier should be fine, it's just failing to start the container. Can you submit a bug report? I see that you tried to in the logs but we didn't receive one.

**Comment by nallux-dozryl** [comment]
@yapishu I don't think sending a bug report will work because GroundSeg is failing to read lanlyd.json. 

@KeepCreatingOnline did you by any chance modify the json file manually? The logs indicate that it's not a valid json file.

**Comment by yapishu** [comment]
(btw, if you wouldn't mind moving to email, shoot us a message at support@nativeplanet.io so we can request additional logs privately)
