### ISSUE TITLE
Load a Ship

### ISSUE THREAD

**Issue by jyng** [Native-Planet/GroundSeg#182]
- Subtitle text should be 24px with -1.4px (4%) letterspacing 
- - Use percentage-based so that you can apply the percentage across all type
- The hover state colors should be less stark (see below)
- Import Pier should use the 'Import' icon

Figma: https://www.figma.com/file/Gwf2q6521ybcvHrff1lA0I/Groundseg?type=design&node-id=713%3A100&mode=design&t=oqY0l1qfaMOHr5OZ-1

![image](https://github.com/Native-Planet/GroundSeg/assets/9557907/137f673c-f6f7-4922-98d0-9ea8938cc953)

**Comment by nallux-dozryl** [comment]
Got it, will get this fixed tomorrow

**Comment by nallux-dozryl** [comment]
fixed
