### ISSUE TITLE
Shutdown& Restart Popup

### ISSUE THREAD

**Issue by jyng** [Native-Planet/GroundSeg#184]
Both of these should be left-aligned. All pop-ups should be left-aligned first unless otherwise specified.

Current:
<img width="862" alt="image" src="https://github.com/Native-Planet/GroundSeg/assets/9557907/f74473e8-64cd-4af4-9a97-08c0467583b3"> <img width="898" alt="image" src="https://github.com/Native-Planet/GroundSeg/assets/9557907/a57d6496-511a-4e1b-a62b-7f256155a459">

Ideal:
<img width="517" alt="image" src="https://github.com/Native-Planet/GroundSeg/assets/9557907/5030a8a2-577e-4f14-a5d8-65aa18f06abd">

Figma: https://www.figma.com/file/Gwf2q6521ybcvHrff1lA0I/Groundseg?type=design&node-id=717%3A245&mode=design&t=vXaW8I1dM18Xhv93-1

**Comment by nallux-dozryl** [comment]
Got it, will be fixed tomorrow

**Comment by nallux-dozryl** [comment]
fixed
