### ISSUE TITLE
Use updated ship card design

### ISSUE THREAD

**Issue by jyng** [Native-Planet/GroundSeg#210]
Use the new ship card designs that showcases the Startram status

```Production```
<img width="1136" alt="image" src="https://github.com/Native-Planet/GroundSeg/assets/9557907/3cff9029-b0e9-4ab6-bbd8-166093572f62">

Furthermore, each of these showcase a state (left to right):
1) StarTram Off, Ship Offline
2) StarTram On, Ship Online
3) StarTram Off, Ship Online

```Design```
<img width="993" alt="image" src="https://github.com/Native-Planet/GroundSeg/assets/9557907/bb626096-00f2-444a-afab-40d52ebf827e">

https://www.figma.com/file/Gwf2q6521ybcvHrff1lA0I/Groundseg?type=design&node-id=606%3A3007&mode=dev

**Comment by nallux-dozryl** [comment]
will get this sorted today

**Comment by nallux-dozryl** [comment]
for storage, the rectangles doesn't convey enough information. The pier's size is limited by the disk size (which is shown in System).

It would make more sense to have it display an absolute value.

**Comment by nallux-dozryl** [comment]
here's how it looks now. I made minor changes to the lower third

![image](https://github.com/Native-Planet/GroundSeg/assets/97745768/c4010d4e-12b9-42e0-a908-51c2e401edaa)

**Comment by jyng** [comment]
Would it make more sense to have the RAM be graphically displayed then?

**Comment by jyng** [comment]
Also, relatedly, I increase the size of the cards, it feels a bit too cramped right now. I would also check to make sure the icons are the same size as well (16 x 16)

https://www.figma.com/file/Gwf2q6521ybcvHrff1lA0I/Groundseg?type=design&node-id=595%3A1630&mode=dev

**Comment by nallux-dozryl** [comment]
Yeah, it would make more sense to graphically display RAM over storage. What do you think about my change?

Icons are lifted directly off figma. They're the correct size.

Used the new cards. It's live now on the remote server.
