### ISSUE TITLE
System Logs Visual Issues

### ISSUE THREAD

**Issue by jyng** [Native-Planet/GroundSeg#211]
- Scroll in the background should be ```position: fixed``` or something similar.
- Not sure what ```Latest``` is suppose to do? Or why it's necessary?
<img width="1511" alt="image" src="https://github.com/Native-Planet/GroundSeg/assets/9557907/cd662ca6-eb2b-49f0-b761-75cc6a3e0290">

**Comment by nallux-dozryl** [comment]
huh, weird that it's broken on yours. Here's how it's suppose to look:
![image](https://github.com/Native-Planet/GroundSeg/assets/97745768/6aa51962-b5b1-4926-b97b-e2383a2e6b06)

- Latest: to jump to the latest timestamp

The log is supposed to start all the way at the bottom (latest) but for some reason that's not working. I'll have to look at it.

**Comment by jyng** [comment]
Shouldn't it always be the latest timestamp?

**Comment by jyng** [comment]
Also it's missing the Copy Button to copy the log.

![image](https://github.com/Native-Planet/GroundSeg/assets/9557907/833399d0-f9ca-4d17-8eda-7bfeff72ec5c)

https://www.figma.com/file/Gwf2q6521ybcvHrff1lA0I/Groundseg?type=design&node-id=606%3A2754&mode=dev
