### ISSUE TITLE
Ship Detail Page

### ISSUE THREAD

**Issue by jyng** [Native-Planet/GroundSeg#221]
Changes:
- Needs to use the light weights for the font
- Sigil is missing
- Background color for the Toggle should also be Green ( See Figma)
- Loom Size Slider needs to be styled like the design
- Start Button should be a button and calendar should be a button as well
- Bottom Buttons should be 24px
```Production```
![image](https://github.com/Native-Planet/GroundSeg/assets/9557907/8b85e006-654c-4ca4-a259-8c3e16f7db9b)

```Design```
https://www.figma.com/file/Gwf2q6521ybcvHrff1lA0I/Groundseg?type=design&node-id=607%3A3175&mode=dev
![image](https://github.com/Native-Planet/GroundSeg/assets/9557907/9b4263ca-f6a7-4400-b136-8562ed7ed349)

**Comment by nallux-dozryl** [comment]
This has been updated
