### ISSUE TITLE
goseg: On first boot after moving to goseg, domain is pointing to the startram, instead of the custom url.

### ISSUE THREAD

**Issue by thelifeandtimes** [Native-Planet/GroundSeg#435]
Per @mopfel-winrux's guidance, I updated my groundseg update path and branch to staging/edge. On the first time trying to access my moon, `~nattev-palnet-sarlev-sarsen`, after that transition, it tried to access via sub.startram.io instead of my previously set up custom domain. 

Expected behavior is for the default to be that I continue to access at the previously set custom domain url.

**Comment by yapishu** [comment]
thanks for letting us know! some of the startram stuff is still fucked up, its on our shortlist, though this might be a ui issue

**Comment by nallux-dozryl** [comment]
pyseg -> goseg migration is probably not 100% right now. So some stuff might not come out right. I don't think there's anything that could permanently fuck anything up tho. Likely just minor config differences -- which will be ironed out in time. 

Is the custom domain missing completely, or did work after switching the URL in the pier settings?

**Comment by nallux-dozryl** [comment]
this should be fixed
