### ISSUE TITLE
goseg: pack schdule doesnt roll over to next month

### ISSUE THREAD

**Issue by mopfel-winrux** [Native-Planet/GroundSeg#505]
![image](https://github.com/Native-Planet/GroundSeg/assets/223191/60b145b9-65ce-47be-8e74-bfa21b0cf25c)

**Comment by nallux-dozryl** [comment]
oops, will get this fixed

**Comment by nallux-dozryl** [comment]
@mopfel-winrux couldn't reproduce this bug. Can you see if it's still happening?

**Comment by mopfel-winrux** [comment]
looks like its fixed. closing
