### ISSUE TITLE
Disk usage monitor fails on paths with spaces in their names

### ISSUE THREAD

**Issue by neonfuz** [Native-Planet/GroundSeg#590]
Disks mounted on paths with spaces in their names fail to show up in the system tab, and the console throws an error every second. 

The error message looks like this, for a disk mounted at "/media/hello world":

`{"time":"2023-11-26T18:17:17.479413064-06:00","level":"WARN","msg":"Error getting disk usage: /media/hello\\040world: no such file or directory"}`

**Comment by nallux-dozryl** [comment]
Fixed with #643
