### ISSUE TITLE
noun/noun.go fails to build

### ISSUE THREAD

**Issue by neonfuz** [Native-Planet/GroundSeg#591]
noun/noun.go fails to build. While the normal build process ignores this file, nix's buildGo121Module attempts to build all modules it can find, so currently the script just deletes the noun folder.

When trying to build you get the following error:

`noun/noun.go:6:2: cannot find module providing package github.com/Native-Planet/go-bitstream: import lookup disabled by -mod=vendor`

The main function has been commented out I believe in an attempt to fix this, but with invalid imports it still fails to build. The noun folder should probably either be deleted or fixed so I can remove this hack from the nix module.

**Comment by neonfuz** [comment]
It seems the important part in this error is the `--mod=vendor` part. There's a huge golang issue about it, and other packagers are running into the same issue for other software.

What seems to be happening is because go-bitstream is not required by the main module, it is not copied into the /vendor directory, and therefore fails when attempting to build noun.go (the only module which uses go-bitstream)

https://github.com/golang/go/issues/26366

**Comment by neonfuz** [comment]
I can't work around the --mod=vendor part, what it does is says to use the vendor folder instead of downloading from the network, which is important for reproducible builds and security.

**Comment by yapishu** [comment]
we need to remove this package entirely, it's not imported because it wasn't completed and we ended up going with an existing 3rd party package

**Comment by yapishu** [comment]
just removed it and tacked in onto https://github.com/Native-Planet/GroundSeg/pull/678

**Comment by neonfuz** [comment]
Confirmed fixed! removed the build hack in the nixos package with 2.0.12 release
