### ISSUE TITLE
Minio: run a single server

### ISSUE THREAD

**Issue by neonfuz** [Native-Planet/GroundSeg#593]
Each instance of minio takes about 100mb of ram. Each ship, even stopped ships, run their own minio instance. This means there's an unnecessary 100mb of ram overhead per ship, running or not.

Instead, you should run a single instance of minio with multi user mode, as documented here:

https://github.com/minio/minio/blob/master/docs/multi-user/README.md

**Comment by mopfel-winrux** [comment]
We didn't do this because we give a domain to each minio instance. This allows users to set a custom s3 domain and move their files out of minio and into another s3 instance w/o losing the reference links. We dont shutdown the minio instance when a ship is shutdown because the right UX is for the images to stay accessible.

**Comment by neonfuz** [comment]
I believe minio is also capable of handling multiple domain names:

https://blog.min.io/secure-multi-tenant-object-storage/
https://github.com/minio/concert/issues/6

Also, is there a way to turn off minio on a ship once you reconfigure to use another s3 provider?

**Comment by neonfuz** [comment]
![Screenshot 2023-11-28 at 7 38 33 PM](https://github.com/Native-Planet/GroundSeg/assets/2590830/268087d6-6374-4caf-bf3b-ab6bd23f6819)

Also just realized each minio spawns 8 (9 total?) threads for each server. This could contribute to the netdata apps plugin using high cpu, I believe more processes = more cpu used by that plugin (I'm not sure if threads count?)

**Comment by neonfuz** [comment]
Upon reading my the docs further I realized the normal way of doing multi tenancy is pretty much running multiple servers anyways. Closing this issue.

https://github.com/minio/minio/tree/master/docs/multi-tenancy
