### ISSUE TITLE
Feature request: automatically configure minio

### ISSUE THREAD

**Issue by neonfuz** [Native-Planet/GroundSeg#594]
Steps to reproduce:

 - boot a new ship
 - log into ship
 - check settings -> remote storage
 - text boxes are empty

**Comment by neonfuz** [comment]
I somehow missed the instructions on doing this manually in the manual. Changed title to reflect that this could be a feature but is not a bug

https://manual.groundseg.app/

**Comment by yapishu** [comment]
We don't want to overwrite S3 settings without explicit direction if there is already a provider set -- will discuss internally checking if the settings are blank

**Comment by neonfuz** [comment]
@yapishu A new thought, what about not staring a minio instance until the user decides to connect it? Currently after you boot a ship minio is sitting there doing nothing but wasting ram until and only if you decide to connect it. If you want to use your own S3 instance there's no way to disable minio per ship (as far as I know)

**Comment by neonfuz** [comment]
Seems off topic so I created a new issue for it: https://github.com/Native-Planet/GroundSeg/issues/644

I'm satisfied with this issue, close it if you want but if you're still internally discussing feel free to leave it open
