### ISSUE TITLE
Booting ship with lapsed startram subscription makes broken ships

### ISSUE THREAD

**Issue by neonfuz** [Native-Planet/GroundSeg#595]
If you attempt to boot a ship with the remote checkbox checked, but your startram subscription is lapsed, there will be no indication of a lapsed subscription on the frontend, and the ship will be completely broken. Even opening the settings page just makes the app go white, so you cannot delete said ships.

**Comment by neonfuz** [comment]
It looks like disabling the startram switch from the dashboard lets me open the settings page again

**Comment by yapishu** [comment]
I believe we fixed this 2.0.10
