### ISSUE TITLE
Netdata apps plugin uses tons of cpu

### ISSUE THREAD

**Issue by neonfuz** [Native-Planet/GroundSeg#604]
![Screenshot 2023-11-28 at 5 22 47 PM](https://github.com/Native-Planet/GroundSeg/assets/2590830/26f58e5f-ce11-4fd2-8fdf-e6b60b8b6d8c)

The netdata apps plugin uses more cpu than groundseg itself. When running over night it used 4x as much cpu as the next process on the machine.

On the Netdata github, there's a closed issue acknowledging high cpu usage but the final comment calls it "not a bug". https://github.com/netdata/netdata/issues/10952

I suggest disabling the apps plugin. I was able to disable the plugin on my local machine. To do so, I did:

 - `docker exec netdata /bin/bash`
 - `vi /etc/netdata/netdata.conf`
 - edit `[plugins]` section to uncomment apps line, and change yes to no
 - save (`esc` `:wq` `enter`) and exit bash
 - `docker restart netdata`

Relevant documentation:
https://learn.netdata.cloud/docs/configuring/daemon-configuration#plugins-section-options

**Comment by neonfuz** [comment]
Confirmed on version 2.0.1-1
Untested on dev

**Comment by yapishu** [comment]
We've disabled this plugin in since 2.0.2
