### ISSUE TITLE
Feature request: multiple users

### ISSUE THREAD

**Issue by neonfuz** [Native-Planet/GroundSeg#607]
I am sharing my groundseg with my roomate. It would be nice if instead of sharing my password with him I could give him a second account which manages it's own ships

**Comment by nallux-dozryl** [comment]
We're currently working on allowing users to manage groundseg from within their ship. Ship settings access if without password, and regular admin access with password

**Comment by nallux-dozryl** [comment]
Completed in #668. Currently waiting Vere 3.0
