### ISSUE TITLE
Groundseg breaks the wi-fi

### ISSUE THREAD

**Issue by chaserene** [Native-Planet/GroundSeg#619]
Debian 12.2 stable
Groundseg 2.0.2
containerd.io 1.6.25-1
docker-buildx-plugin 0.11.2-1
docker-ce 24.0.7-1
docker-ce-cli 24.0.7-1
docker-compose-plugin 2.21.0-1

I uninstalled Groundseg and all packages related to Docker following [this](https://docs.docker.com/engine/install/debian/#uninstall-old-versions) guide. I installed Docker via the above packages following [these](https://docs.docker.com/engine/install/debian/#install-from-a-package) instructions. I started the Docker service and successfully verified the installation via `sudo docker run hello-world`, then ran [groundseg_install.sh](https://github.com/Native-Planet/GroundSeg/blob/e8dc74faac170eafa91c6c1f00626a7b1106c205/release/groundseg_install.sh).

after seeing that the install script was successful, I went to the browser to set up Groundseg. a few seconds after I finished the initial wizard (when the empty list of ships first become visible), my wi-fi card disconnected from my router lost sight of all signal sources (the list of detected wireless sources is empty). if I turn off the wi-fi then turn it on again, I can see signal sources and connect to them for about 10 seconds, then they disappear again.

I tried restarting the computer and just watching what happens. the wi-fi works at startup, but the above happens immediately after I open GNOME's [system menu](https://help.gnome.org/users/gnome-help/stable/shell-introduction.html.en#systemmenu). if I do nothing, the disconnect still happens, only with a 5-10 minute delay (at least judging by the wi-fi icon in the top bar).

Groundseg's system logs are repeating a stream of the following entries:

````
{"time":"...","level":"ERROR","msg":"Check internet access error: dial tcp 1.1.1.1:53: connect: connection refused"}

{"time":"...","level":"INFO","msg":"Accesspoint already stopped"}

{"time":"...","level":"ERROR","msg":"Error activating C2C mode: exec: \"hostapd\": executable file not found in $PATH"}
````

I tried plugging an Ethernet cable into the computer. this brought back connectivity for the rest of the system, but not Groundseg. (not that this would be considered a solution, I don't want this computer to be bound by a cable for networking.) if I go to the System section in Groundseg, under Connection, I see the wi-fi turned on and an empty field under Network Name. if I turn it off, it turns itself on again in about 20 seconds, and first displays the name of my default wireless connection under Network Name, but then it becomes empty again.

uninstalling Groundseg using [groundseg_uninstall.sh](https://github.com/Native-Planet/GroundSeg/blob/20bf58a789133655fd8c13013a47003c0c4edfda/release/groundseg_uninstall.sh) and restarting the computer restored the wi-fi.

**Comment by yapishu** [comment]
Hi @chaserene , GroundSeg's behavior is to broadcast a "connect-to-connect" wifi network if it does not detect an internet connection, so that you can connect to it and configure it to connect to your actual wifi network, a la Chromecast. This is another reason we recommend using a dedicated device for GS, as it is built with that assumption in mind. The issue you are experiencing is downstream from the one you reported previously, because GS is not detecting an internet connection for whatever reason -- I think we can implement a fix to prevent the weird wifi behavior, I will take a look in the next day or two; however, I'm uncertain what the ultimate cause is for your connection issues, since I don't have knowledge of your host or network environment.

**Comment by yapishu** [comment]
By the way, we shipped an update yesterday (2.0.3) that had a bugfix for DNS resolution issues, I don't think it's relevant since you can't route to an IP but I would still give it a shot

**Comment by SaulMoonves** [comment]
As of yesterday, this or a similar bug is happening to me on a NativePlanet dedicated device (I bought a Tellurian 1.0 from you guys and just hooked it up a few days ago.) It worked for a while and then lost wifi and only a network cable would bring back network.

```
Dec 07 22:30:26 nativeplanet groundseg[1319]: {"time":"2023-12-07T22:30:26.425764686-08:00","level":"ERROR","msg":"Check internet access error: dial tcp 1.1.1.1:53: connect: network is unreachable"}
Dec 07 22:30:31 nativeplanet groundseg[1319]: {"time":"2023-12-07T22:30:31.42538817-08:00","level":"ERROR","msg":"Check internet access error: dial tcp 1.1.1.1:53: connect: network is unreachable"}
Dec 07 22:30:32 nativeplanet dnsmasq[319699]: Maximum number of concurrent DNS queries reached (max: 150)
Dec 07 22:30:36 nativeplanet groundseg[1319]: {"time":"2023-12-07T22:30:36.425631907-08:00","level":"ERROR","msg":"Check internet access error: dial tcp 1.1.1.1:53: connect: network is unreachable"}
Dec 07 22:30:41 nativeplanet groundseg[1319]: {"time":"2023-12-07T22:30:41.425496559-08:00","level":"ERROR","msg":"Check internet access error: dial tcp 1.1.1.1:53: connect: network is unreachable"}
Dec 07 22:30:46 nativeplanet groundseg[1319]: {"time":"2023-12-07T22:30:46.424991907-08:00","level":"ERROR","msg":"Check internet access error: dial tcp 1.1.1.1:53: connect: network is unreachable"}
```

I have switched to GroundSeg edge but now have a different error, will open a separate issue.

**Comment by yapishu** [comment]
GS now only does C2C mode on NP devices, and is less aggressive about switching ([v2.0.11](https://github.com/Native-Planet/GroundSeg/releases/tag/v2.0.11))
