### ISSUE TITLE
Expose groundseg directory as environment variable

### ISSUE THREAD

**Issue by neonfuz** [Native-Planet/GroundSeg#649]
Currently the nix package patches the sources to replace `/opt/nativeplanet/groundseg` with `/var/lib/groundseg`. It would be closer to possible to use the vanilla groundseg binary if this was exposed as an environment variable instead of being hardcoded in the binary.

**Comment by yapishu** [comment]
this actually is supposed to be [already exposed](https://github.com/Native-Planet/GroundSeg/blob/master/goseg/config/config.go#L199) via env var, I think this was just something sloppy that I didn't clean up; I'll fix this for next release

**Comment by yapishu** [comment]
https://github.com/Native-Planet/GroundSeg/pull/678

**Comment by yapishu** [comment]
released in 2.0.12
