### ISSUE TITLE
All links lead to Twitter

### ISSUE THREAD

**Issue by aliddell** [Native-Planet/GroundSeg#699]
I noticed in the GroundSeg UI that Twitter, email, and Urbit links all point to Twitter: https://github.com/search?q=repo%3ANative-Planet%2FGroundSeg+twitter&type=code

<img width="529" alt="image" src="https://github.com/Native-Planet/GroundSeg/assets/844464/c6fb4dd9-8d76-4981-9468-3244170b4a66">

I'd open the PR myself but I don't know what the hrefs ought to be.

**Comment by nallux-dozryl** [comment]
@aliddell this is fixed in the upcoming update https://github.com/Native-Planet/GroundSeg/blob/v2.1.0-rc0/ui/src/routes/system/Support.svelte#L32
